import '../styles/globals.css';
import Navbar from '../components/Navbar';
import HostNavbar from '../components/HostNavbar';
import Footer from '../components/Footer';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import type { Metadata } from 'next';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();

  // Définir les chemins pour lesquels le HostNavbar doit être utilisé
  const hostRoutes = [
    '/host/login',
    '/host/register',
    '/host/dashboard',
    '/host/properties',
    '/host/documents',
    '/host/notifications',
    '/host/edit-property',
    '/host/view-property',
    '/host/add-availability',
    '/host/edit-availability',
    '/host/service/host_service',
    '/host/add-property'
  ];

  const isHostRoute = hostRoutes.includes(router.pathname);

  return (
      <>
        {isHostRoute ? <HostNavbar /> : <Navbar />}
        <Component {...pageProps} />
        <Footer /> {/* jouter footer ici */}
      </>
  );
}

export default MyApp;
